# Generated by Django 5.0 on 2024-02-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Input",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=70)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
